# Generated by Django 6.0.2 on 2026-02-21 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0004_alter_warehouse_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature_no', models.CharField(db_index=True, max_length=32, verbose_name='Номенкл №')),
                ('bso', models.CharField(blank=True, max_length=64, verbose_name='БСО')),
                ('name', models.CharField(blank=True, max_length=512, verbose_name='Наименование')),
                ('uom', models.CharField(blank=True, max_length=32, verbose_name='Ед. изм.')),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='Количество')),
                ('date_in', models.DateField(blank=True, null=True, verbose_name='Дата прихода на склад')),
                ('date_out', models.DateField(blank=True, null=True, verbose_name='Дата расхода')),
                ('months_no_move', models.IntegerField(blank=True, null=True, verbose_name='Месяцев без движения')),
                ('loaded_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='warehouse.department', verbose_name='Подразделение')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Остаток (текущий)',
                'verbose_name_plural': 'Остатки (текущие)',
                'indexes': [models.Index(fields=['department', 'warehouse'], name='idx_stock_dep_wh'), models.Index(fields=['nomenclature_no'], name='idx_stock_nom'), models.Index(fields=['months_no_move'], name='idx_stock_months')],
            },
        ),
    ]
