# Generated by Django 6.0.2 on 2026-02-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstock',
            name='months_no_move',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Месяцев без движения'),
        ),
    ]
