# Generated by Django 6.0.2 on 2026-02-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_currentstock_months_no_move'),
        ('warehouse', '0004_alter_warehouse_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstock',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='currentstock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Цена'),
        ),
        migrations.AddIndex(
            model_name='currentstock',
            index=models.Index(fields=['price'], name='idx_stock_price'),
        ),
        migrations.AddIndex(
            model_name='currentstock',
            index=models.Index(fields=['amount'], name='idx_stock_amount'),
        ),
    ]
