# Generated by Django 6.0.2 on 2026-02-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_currentstock_amount_currentstock_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstock',
            name='date_in_ngmk',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прихода в НГМК'),
        ),
    ]
