# Generated by Django 6.0.2 on 2026-02-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_department_warehouse_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Код склада'),
        ),
    ]
