# Generated by Django 6.0.2 on 2026-02-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='№ п/п')),
                ('catalog_number', models.CharField(max_length=100, verbose_name='Каталожный №')),
                ('nom_number', models.CharField(max_length=100, verbose_name='Номенклатурный №')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Марка')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('unit', models.CharField(blank=True, max_length=100, verbose_name='Узел')),
                ('months_without_movement', models.IntegerField(default=0, verbose_name='Месяцев без движения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
                'ordering': ['number'],
            },
        ),
    ]
